version: '3'

services:
  jenkins-service-build:
    build: ./jenkins
    volumes:
      - "/opt/jenkins/jenkins-data:/root/.jenkins"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"

  nginx-service-build:
    image: nginx:alpine
    ports:
     - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/www:/data/www"
    depends_on:
      - jenkins-service-build
